[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "chip8"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
macroquad = "0.4"